services:
  vllm-demo:
    image: nvcr.io/nvidia/vllm:26.01-py3
    container_name: vllm-demo
    network_mode: "host"
    ipc: host
    ports:
      - "8001:8000" # VLLM API access
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    command: >
      vllm serve "Qwen/Qwen3-30B-A3B" 
        --served-model-name Qwen3-30B-A3B 
        --port 8000 
        --max-model-len 131072 
        --gpu-memory-utilization 0.95 
        --kv-cache-dtype fp8 
        --tensor-parallel-size 1 
        --max-num-seqs 16 
        --enable-prefix-caching 
        --attention-backend flashinfer 
        --quantization fp8
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]